/**
 * The whole point of this file: run the TypeScript port against the exact bytes
 * the Python reference implementation produces.
 *
 * `shared/test-vectors.json` is generated by `hoermoles_ble.interop` and guarded
 * by `test_interop.py`, so it cannot go stale without CI noticing. If a test
 * here fails, the two implementations disagree about the wire format - which is
 * the only kind of bug that would otherwise show up as a drive silently
 * refusing to open.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { fromHex, toHex } from '../src/bytes.js';
import { signerFromBytes } from '../src/crypto.js';
import {
  NotificationReassembler,
  batchMenuGroupsForSelectedProperties,
  buildGetLogFrame,
  buildGetPropertiesFrame,
  buildGetSelectedPropertiesFrame,
  buildReadServiceDataFrame,
  buildRegisterRootFrame,
  buildRegistrationFrame,
  buildSetPropertiesFrame,
  buildSwitchRelaisFrame,
  deriveRootKey,
  parseQrCode,
  parseSignedNotification,
  productClassAndIdFromQrPrefix,
  serialNoFromQrPrefix,
  type Signer,
} from '../src/protocol.js';

interface Vectors {
  constants: { root_id: number; root_key: string; challenge: string; timestamp: number };
  frames: { name: string; function: string; args: Record<string, unknown>; frame: string }[];
  notifications: { name: string; payload: string; expected: Record<string, unknown> }[];
  reassembler: { name: string; events: string[]; expected_per_event: [number, string][][] }[];
  qr_codes: { name: string; qr_text: string; expected: Record<string, unknown> }[];
  misc: {
    derive_root_key: { register_key: string; device_wire_value: string; expected_root_key: string };
    batch_menu_groups: { input: number[]; expected: number[][] }[];
  };
}

const vectorsPath = fileURLToPath(new URL('../../../../shared/test-vectors.json', import.meta.url));
const vectors: Vectors = JSON.parse(readFileSync(vectorsPath, 'utf8'));

const ROOT_ID = vectors.constants.root_id;
const CHALLENGE = fromHex(vectors.constants.challenge);
const TIMESTAMP = vectors.constants.timestamp;

let signer: Signer;
async function getSigner(): Promise<Signer> {
  signer ??= await signerFromBytes(fromHex(vectors.constants.root_key));
  return signer;
}

function vector(name: string) {
  const found = vectors.frames.find((entry) => entry.name === name);
  if (!found) throw new Error(`No test vector named '${name}' - regenerate shared/test-vectors.json`);
  return found;
}

describe('frame builders match the Python reference byte for byte', () => {
  it('switch_relais channel 1', async () => {
    const frame = await buildSwitchRelaisFrame(ROOT_ID, 1, await getSigner(), CHALLENGE, TIMESTAMP);
    expect(toHex(frame)).toBe(vector('switch_relais_channel_1').frame);
  });

  it('switch_relais channel 6', async () => {
    const frame = await buildSwitchRelaisFrame(ROOT_ID, 6, await getSigner(), CHALLENGE, TIMESTAMP);
    expect(toHex(frame)).toBe(vector('switch_relais_channel_6').frame);
  });

  it('register_root with the hardcoded default username', async () => {
    const frame = await buildRegisterRootFrame(await getSigner(), CHALLENGE);
    expect(toHex(frame)).toBe(vector('register_root_default_username').frame);
  });

  it('register_root with a custom username', async () => {
    const frame = await buildRegisterRootFrame(await getSigner(), CHALLENGE, 'hoermoles');
    expect(toHex(frame)).toBe(vector('register_root_custom_username').frame);
  });

  it('get_properties', async () => {
    const frame = await buildGetPropertiesFrame(ROOT_ID, await getSigner(), CHALLENGE);
    expect(toHex(frame)).toBe(vector('get_properties').frame);
  });

  it('get_selected_properties pads a single group to four', async () => {
    const frame = await buildGetSelectedPropertiesFrame(ROOT_ID, [16], await getSigner(), CHALLENGE);
    expect(toHex(frame)).toBe(vector('get_selected_properties_one_group').frame);
  });

  it('get_selected_properties with a full batch', async () => {
    const frame = await buildGetSelectedPropertiesFrame(
      ROOT_ID,
      [1, 2, 3, 4],
      await getSigner(),
      CHALLENGE,
    );
    expect(toHex(frame)).toBe(vector('get_selected_properties_four_groups').frame);
  });

  it('set_properties', async () => {
    const frame = await buildSetPropertiesFrame(ROOT_ID, [[16, 1]], await getSigner(), CHALLENGE);
    expect(toHex(frame)).toBe(vector('set_properties_single').frame);
  });

  it('set_properties encodes negative values as signed int16', async () => {
    const frame = await buildSetPropertiesFrame(ROOT_ID, [[2, -1]], await getSigner(), CHALLENGE);
    expect(toHex(frame)).toBe(vector('set_properties_negative_value').frame);
  });

  it('get_log', async () => {
    const frame = await buildGetLogFrame(ROOT_ID, await getSigner(), CHALLENGE);
    expect(toHex(frame)).toBe(vector('get_log').frame);
  });

  it('read_service_data', async () => {
    const frame = await buildReadServiceDataFrame(ROOT_ID, await getSigner(), CHALLENGE);
    expect(toHex(frame)).toBe(vector('read_service_data').frame);
  });

  it('registration (encrypted routing, no HMAC)', () => {
    const entry = vector('registration_encrypted');
    const frame = buildRegistrationFrame(fromHex(entry.args.rsa_encrypted_key_hex as string));
    expect(toHex(frame)).toBe(entry.frame);
  });
});

describe('notification parsing matches the Python reference', () => {
  for (const testCase of vectors.notifications) {
    it(testCase.name, () => {
      const parsed = parseSignedNotification(fromHex(testCase.payload));
      const expected = testCase.expected;

      expect(toHex(parsed.challenge)).toBe(expected.challenge);
      expect(parsed.notifType).toBe(expected.notif_type);
      expect(toHex(parsed.payload)).toBe(expected.payload);
      expect(parsed.rootId).toBe(expected.root_id ?? null);
      expect(parsed.rootKeyWire === null ? null : toHex(parsed.rootKeyWire)).toBe(
        expected.root_key_wire ?? null,
      );
      expect(parsed.properties).toEqual(expected.properties ?? null);
      expect(parsed.serviceData).toEqual(expected.service_data ?? null);

      const expectedLog = expected.log_entry as [number, number, string] | null;
      if (expectedLog === null) {
        expect(parsed.logEntry).toBeNull();
      } else {
        expect(parsed.logEntry).not.toBeNull();
        expect(parsed.logEntry!.logTag).toBe(expectedLog[0]);
        expect(parsed.logEntry!.timestampRaw).toBe(expectedLog[1]);
        expect(toHex(parsed.logEntry!.data)).toBe(expectedLog[2]);
      }
    });
  }
});

describe('envelope reassembly matches the Python reference', () => {
  for (const testCase of vectors.reassembler) {
    it(testCase.name, () => {
      const reassembler = new NotificationReassembler();
      const actual = testCase.events.map((event) =>
        reassembler.feed(fromHex(event)).map(({ ioId, payload }) => [ioId, toHex(payload)]),
      );
      expect(actual).toEqual(testCase.expected_per_event);
    });
  }
});

describe('QR code parsing matches the Python reference', () => {
  for (const testCase of vectors.qr_codes) {
    it(testCase.name, () => {
      const { prefix, der } = parseQrCode(testCase.qr_text);
      expect(prefix).toBe(testCase.expected.prefix);
      expect(toHex(der)).toBe(testCase.expected.der);

      const serial = serialNoFromQrPrefix(prefix);
      expect(serial === null ? null : serial.toString()).toBe(
        testCase.expected.serial_no === null ? null : String(testCase.expected.serial_no),
      );

      const product = productClassAndIdFromQrPrefix(prefix);
      expect(product?.productClass ?? null).toBe(testCase.expected.product_class ?? null);
      expect(product?.productId ?? null).toBe(testCase.expected.product_id ?? null);
    });
  }
});

describe('miscellaneous vectors', () => {
  it('derive_root_key XORs the device value with our register key', () => {
    const { register_key, device_wire_value, expected_root_key } = vectors.misc.derive_root_key;
    expect(toHex(deriveRootKey(fromHex(register_key), fromHex(device_wire_value)))).toBe(
      expected_root_key,
    );
  });

  for (const [index, testCase] of vectors.misc.batch_menu_groups.entries()) {
    it(`batch_menu_groups case ${index}: [${testCase.input.join(', ')}]`, () => {
      expect(batchMenuGroupsForSelectedProperties(testCase.input)).toEqual(testCase.expected);
    });
  }
});
